#!/bin/sh

if [ -f "htldoc.nix" ]; then
	htldocUrl=$(nix eval --expr 'let config = (import ./htldoc.nix {}); in if builtins.hasAttr "htldocVersion" config then config.htldocVersion else "github:c2vi/htldoc/master"' --impure)
	nix run $htldocUrl -- $@
else 
	nix run github:c2vi/htldoc/master -- $@
fi

