#!/bin/sh

if [ -f "htldoc.nix" ]; then
  echo -en ""
else 
    echo "There is not htldoc.nix in this directory" >&2
    exit 1
fi

htldocUrl=$(nix eval --expr 'let config = (import ./htldoc.nix {}); in if builtins.hasAttr "htldocVersion" config then config.htldocVersion else "github:c2vi/htldoc/master"' --impure)

nix run $htldocUrl
